CREATE TABLE IF NOT EXISTS specialties (
	id_specialty INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS insurances (
	id_insurance INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	coverage_percentage INTEGER NOT NULL CHECK (coverage_percentage BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS treatments (
	id_treatment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	treatment_code VARCHAR(20) NOT NULL UNIQUE,
	description TEXT NOT NULL,
	cost NUMERIC(12,2) NOT NULL CHECK (cost >= 0)
);

CREATE TABLE IF NOT EXISTS patients (
	id_patient INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(200) NOT NULL,
	insurance_id INTEGER NOT NULL REFERENCES insurances(id_insurance) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS doctors (
	id_doctor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	id_specialty INTEGER NOT NULL REFERENCES specialties(id_specialty) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS appointments (
	id_appointment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	appointment_code VARCHAR(20),
	appointment_date TIMESTAMP NOT NULL,
	patient_id INTEGER NOT NULL REFERENCES patients(id_patient) ON UPDATE CASCADE ON DELETE RESTRICT,
	doctor_id INTEGER NOT NULL REFERENCES doctors(id_doctor) ON UPDATE CASCADE ON DELETE RESTRICT,
	treatment_id INTEGER NOT NULL REFERENCES treatments(id_treatment) ON UPDATE CASCADE ON DELETE RESTRICT,
	amount_paid NUMERIC(12,2) NOT NULL CHECK (amount_paid >= 0)
);

CREATE TABLE IF NOT EXISTS migration (
	appointment_id VARCHAR(20) PRIMARY KEY,
	appointment_date DATE,
	patient_name VARCHAR(100),
	patient_email VARCHAR(100),
	patient_phone VARCHAR(30),
	patient_address VARCHAR(200),
	doctor_name VARCHAR(100),
	doctor_email VARCHAR(100),
	specialty VARCHAR(100),
	treatment_code VARCHAR(20),
	treatment_description VARCHAR(200),
	treatment_cost NUMERIC(12,2),
	insurance_provider VARCHAR(100),
	coverage_percentage INTEGER,
	amount_paid NUMERIC(12,2) NOT NULL
);

ALTER TABLE patients
	ADD COLUMN IF NOT EXISTS insurance_id INTEGER;

ALTER TABLE patients
	DROP CONSTRAINT IF EXISTS patients_insurance_id_fkey,
	ADD CONSTRAINT patients_insurance_id_fkey
	FOREIGN KEY (insurance_id) REFERENCES insurances(id_insurance)
	ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE appointments
	ADD COLUMN IF NOT EXISTS appointment_code VARCHAR(20),
	ADD COLUMN IF NOT EXISTS amount_paid NUMERIC(12,2) DEFAULT 0;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_specialties_description') THEN
		ALTER TABLE specialties ADD CONSTRAINT uq_specialties_description UNIQUE (description);
	END IF;

	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_appointments_code') THEN
		ALTER TABLE appointments ADD CONSTRAINT uq_appointments_code UNIQUE (appointment_code);
	END IF;
END $$;