CREATE TABLE IF NOT EXISTS "patients" (
	"id_patient" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"phone" VARCHAR(50) NOT NULL,
	"address" VARCHAR(50) NOT NULL,
	"insurance_id" INTEGER,
	PRIMARY KEY("id_patient")
);




CREATE TABLE IF NOT EXISTS "doctors" (
	"id_doctor" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	--  
	"email" VARCHAR(50) NOT NULL UNIQUE,
	"id_specialty" INTEGER NOT NULL,
	PRIMARY KEY("id_doctor")
);

CREATE TABLE IF NOT EXISTS "insurances" (
	"id_insurance" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	"coverage_percentage" INTEGER NOT NULL,
	PRIMARY KEY("id_insurance")
);

CREATE TABLE IF NOT EXISTS "appointments" (
	"id_appointment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"appointment_date" TIMESTAMP NOT NULL,
	"patient_id" INTEGER NOT NULL,
	"doctor_id" INTEGER NOT NULL,
	"treatment_id" INTEGER NOT NULL,
	PRIMARY KEY("id_appointment")
);

CREATE TABLE IF NOT EXISTS "treatments" (
	"id_treatment" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"description" TEXT NOT NULL,
	"cost" INTEGER NOT NULL,
	"treatment_code" VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY("id_treatment")
);

CREATE TABLE IF NOT EXISTS "specialties" (
	"id_specialty" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"description" VARCHAR(50) NOT NULL,
	PRIMARY KEY("id_specialty")
);


CREATE TABLE IF NOT EXISTS "migration" (
 appointment_id VARCHAR(20) PRIMARY KEY,
    appointment_date DATE,
    patient_name VARCHAR(100),
    patient_email VARCHAR(100),
    patient_phone VARCHAR(20),
    patient_address VARCHAR(150),
    doctor_name VARCHAR(100),
    doctor_email VARCHAR(100),
    specialty VARCHAR(100),
    treatment_code VARCHAR(20),
    treatment_description VARCHAR(150),
    treatment_cost NUMERIC(10,2),
    insurance_provider VARCHAR(100),
    coverage_percentage INT,
    amount_paid NUMERIC(10,2) NOT NULL
);


ALTER TABLE "appointments"
ADD FOREIGN KEY("patient_id") REFERENCES "patients"("id_patient")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "appointments"
ADD FOREIGN KEY("doctor_id") REFERENCES "doctors"("id_doctor")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "appointments"
ADD FOREIGN KEY("treatment_id") REFERENCES "treatments"("id_treatment")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "patients"
ADD FOREIGN KEY("insurance_id") REFERENCES "insurances"("id_insurance")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "doctors"
ADD FOREIGN KEY("id_specialty") REFERENCES "specialty"("id_specialty")
ON UPDATE CASCADE ON DELETE CASCADE; 
`;